### ISSUE TITLE
Cannot open a console on production server

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#214]
When trying to run `RAILS_ENV=production bundle exec rails c`, I'm getting...
```
/usr/local/lib/ruby/2.2.0/irb/completion.rb:9:in `require': cannot load such file -- readline (LoadError)
	from /usr/local/lib/ruby/2.2.0/irb/completion.rb:9:in `<top (required)>'
```

Feel like we've bumped into something similar before, but can't remember what it was.

**Done when** I can open a rails console in a production environment on an AWS server.

Just figure out what needs to be done with this ticket. If there's additional changes that need to be made to the mla-playbooks, or openvault3_deploy, then create those tickets as needed.

**Comment by mccalluc** [comment]
@afred : You created a new key for this server? ov1.wgbh-mla-test.org? Could you give me a copy?
